In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-0.72491724,  0.80094174,  0.50272248, -0.53579345,  0.80940147,
       -0.3668661 , -0.31055107,  0.50142854,  1.85514652, -0.64513298])

In [7]:
B = np.random.randn(10)

In [8]:
B

array([-0.81152316,  0.91562184, -0.10958681, -2.46774665,  1.37926639,
       -0.12799891,  1.60443129, -0.24645544,  0.58296912, -0.4727147 ])

In [10]:
# Binary Functions
np.add(A,B)

array([-1.5364404 ,  1.71656358,  0.39313568, -3.0035401 ,  2.18866786,
       -0.49486501,  1.29388022,  0.25497309,  2.43811564, -1.11784768])

In [13]:
np.minimum(A,B)

array([-0.81152316,  0.80094174, -0.10958681, -2.46774665,  0.80940147,
       -0.3668661 , -0.31055107, -0.24645544,  0.58296912, -0.64513298])