In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([ 0.66707399,  0.18714465, -0.71418557, -1.26900785, -0.73420897,
        1.17128252, -0.71123433,  0.90485234, -1.19343838,  0.74367392])

In [7]:
B = np.random.randn(10)

In [8]:
B

array([-0.0434656 ,  0.34296736, -0.05389401, -0.40663306, -0.30894203,
       -0.54680793, -0.53912356, -0.46406235, -0.14203726, -0.34207517])

In [9]:
# Binary Functions
np.add(A,B)

array([ 0.62360839,  0.53011201, -0.76807959, -1.67564091, -1.043151  ,
        0.62447459, -1.25035789,  0.44078999, -1.33547564,  0.40159875])

In [10]:
np.minimum(A,B)

array([-0.0434656 ,  0.18714465, -0.71418557, -1.26900785, -0.73420897,
       -0.54680793, -0.71123433, -0.46406235, -1.19343838, -0.34207517])